version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: "postgres_pm"
    ports:
      - "5432:5432"
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    env_file: env_file_pm
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
