# Generated by Django 2.2.2 on 2019-07-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service name')),
                ('status', models.BooleanField(default=True, verbose_name='Service status')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last synchronization')),
                ('frequency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Service frequency')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='User name')),
                ('token', models.CharField(max_length=255, verbose_name='User token')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refresh Token')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='core.Service', verbose_name='Service token')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Tag name')),
                ('service', models.ManyToManyField(related_name='tags', to='core.Service', verbose_name='Service')),
                ('user', models.ManyToManyField(related_name='tags', to='core.User', verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ManyToManyField(related_name='service', to='core.User', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Timestamp')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender message user')),
                ('text', models.TextField(max_length=2000, verbose_name='Text in message')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Service', verbose_name='Service messages')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Tag', verbose_name='Tag messages')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.User', verbose_name='User messages')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.CharField(max_length=255, verbose_name='Message log')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.Service', verbose_name='Log service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.User', verbose_name='Log user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('url_download', models.CharField(max_length=255, verbose_name='Url download for file')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Message', verbose_name='File message')),
            ],
        ),
    ]
