# Generated by Django 2.2.2 on 2019-06-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='User name')),
                ('token', models.CharField(max_length=255, verbose_name='User token')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Refresh Token')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='core.Services', verbose_name='Service token')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tags name')),
                ('service', models.ManyToManyField(related_name='tags', to='core.Services', verbose_name='Service')),
                ('user', models.ManyToManyField(related_name='tags', to='core.User', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Timestamp')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender message user')),
                ('text', models.TextField(max_length=2000, verbose_name='Text in message')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Services', verbose_name='Service messages')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Tags', verbose_name='Tag messages')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.User', verbose_name='User messages')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.CharField(max_length=255, verbose_name='Message log')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.Services', verbose_name='Log service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.User', verbose_name='Log user')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('url_download', models.CharField(max_length=255, verbose_name='Url download for file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Messages', verbose_name='File message')),
            ],
        ),
    ]
