# Generated by Django 2.2.2 on 2019-07-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag url to confluence'),
        ),
    ]
