# Generated by Django 2.2.2 on 2019-07-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.CharField(blank=True, default='url', max_length=255, null=True, verbose_name='Tag url to confluence'),
        ),
    ]
