# Generated by Django 2.2.2 on 2019-07-02 23:10

from django.db import migrations, models
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190626_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
