# Generated by Django 2.2.2 on 2019-07-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'create_user_and_services'),
        ('core', '0003_auto_20190708_0407'),
    ]

    operations = [
    ]
