# Generated by Django 2.2.2 on 2019-07-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_googlecredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleCredential',
        ),
    ]
