# Generated by Django 2.2.2 on 2019-07-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_log_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='url',
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Message Id'),
        ),
        migrations.AddField(
            model_name='service',
            name='connected',
            field=models.BooleanField(default=False, verbose_name='Service connected'),
        ),
    ]
