# Generated by Django 2.2.2 on 2019-07-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190710_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='url',
        ),
    ]
