# Generated by Django 2.2.2 on 2019-07-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190712_1458'),
        ('core', 'services_create'),
    ]

    operations = [
    ]
