# Generated by Django 2.2.2 on 2019-06-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20190621_0119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Emails',
        ),
    ]
