# Generated by Django 2.2.2 on 2019-06-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20190621_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
    ]
