import pytz

EVERYDAY = 'everyday'
EVERY_WEEK = 'everyweek'
EVERY_MONTH = 'everymonth'
DAY = 1
MONTH = 30
WEEK = 7
MINUTE_DAY = 1440
MINUTE_WEEK = 10080
MINUTE_MONTH = 44640
LOCAL = pytz.timezone('Asia/Bishkek')
TIMESTAMP_WITH_UTC = 36
TIMESTAMP_WITHOUT_UTC = 32
